name: Run docker-compose build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: docker-compose build --no-cache 
        
      - name: Run docker-compose up movietest
        run: docker-compose up 
        
        
